{
 "title": "Logging Dashboard via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Service",
    "query": "label_values({container=~\".+\"}, container)"
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": "label_values({container=~\".+\"}, pod)"
   },
   { "name": "level", "label": "level", "query": "error,  warn,  info" },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "日志总条数",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container_name\", pod=~\"$pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "错误日志条数：$searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\"$container_name\", pod=~\"$pod_name\"} | json | line_format \"{{.log}}\" | logfmt | __error__=\"\" | level=\"error\" [$__interval]))"
    }
   ]
  },
  {
   "title": "每分钟产生的日志数量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container_name\", pod=~\"$pod_name\", level=~\"$level\"})[1m]))",
     "legendFormat": "日志条数"
    }
   ]
  },
  {
   "title": "按应用统计日志条数",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container_name\", pod=~\"$pod_name\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\")[$__range])) by (container)",
     "legendFormat": "{{container}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "按日志级别统计条数",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time(({container=~\"$container_name\", pod=~\"$pod_name\"} | json | line_format \"{{.log}}\" | logfmt | __error__=\"\" |~ \"(?i)$searchable_pattern\")[$__range]))",
     "legendFormat": "{{level}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=~\"$container_name\", pod=~\"$pod_name\"} |~ \"(?i)$searchable_pattern\" | json | line_format \"{{.log}}\" | logfmt | level=~\"$level\""
    }
   ]
  },
  {
   "title": "每秒日志数据量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(bytes_rate({container=~\"$container_name\", pod=~\"$pod_name\"}[1m]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container_name\", pod=~\"$pod_name\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per Pod",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(({container=~\"$container_name\", pod=~\"$pod_name\", level=~\"$level\"} |~ \"(?i)$searchable_pattern\")[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container_name\", pod=~\"$pod_name\"})[$__interval])) by (stream)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container=~\"$container_name\", stream=~\"$stream\", pod=~\"$pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({container=~\"$container_name\", stream=~\"$stream\", pod=~\"$pod_name\"})[$__interval]))"
    }
   ]
  }
 ]
}